site_name: RoboDuck
theme: 'material'
plugins:
  - search
  # From https://github.com/mkdocstrings/mkdocstrings/issues/365#issuecomment-1017748179
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: true
            show_category_heading: true
            members_order: source
            show_if_no_docstring: true
            docstring_style: numpy
            filters: ["!^_"]
markdown_extensions:
  # TODO Trying to get docstring params to be parsed correctly. Just shows type, not name, atm.
  - pymdownx.superfences:
      custom_fences:
        - name: python
          class: python
          format: !!python/str '{lineno} {pyobject}'

# Bullets below will be tabs in left navbar.
nav:
  - About: README.md
  - debug.md
  - errors.md
  - logging.md
  - magic.md
  - CLI: cli/cli.md
  - shell.md
  - utils.md
  - IPython utils: ipy_utils.md
  - decorators.md
  - Custom Prompts: custom_prompts.md
  - config.md
